mysite1/accounts/urls.py
from django.urls import path

from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('authentication/', authentication, name='authentication'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile_view, name='profile'),
]

mysite1/core/urls.py
from django.urls import path

from core.views import *

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('services/', services, name='services'),
    path('contact', contact, name='contact')
]

mysite1/mysite1/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mysite1 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('rooms/', include('rooms.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite1/accounts/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models


class User(AbstractUser):
    name = models.CharField(verbose_name='Имя', max_length=255, default='Безымянный')
    email = models.EmailField(verbose_name='Email', max_length=255, unique=True)
    username = models.CharField(verbose_name='Имя пользователя', max_length=255, blank=True, unique=False)
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

mysite1/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from .models import User


class RegistrationForm(UserCreationForm):
    name = forms.CharField(required=True, label='Ваше имя и фамилия')
    email = forms.EmailField(required=True, label='Ваш Email-адрес')

    class Meta:
        model = User
        fields = ('name', 'email', 'password1', 'password2')


class LoginForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput)

    def authenticate_user(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        return user

mysite1/accounts/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout

import rooms.models
from accounts.forms import *


def authentication(request):
    if request.method == 'POST':
        registration_form = RegistrationForm(request.POST)
        if registration_form.is_valid():
            user = registration_form.save()  # Сохранение пользователя
            login(request, user)  # Авторизация пользователя
            messages.add_message(request, messages.SUCCESS,
                                 f"Здравствуйте, {user.name}! Вы успешно зарегистрировались.")
            return redirect('accounts:profile')
    else:
        registration_form = RegistrationForm()

    # Обработка отправки формы входа
    login_form = LoginForm(request.POST or None)
    if request.method == 'POST' and login_form.is_valid():
        user = login_form.authenticate_user()
        if user:
            login(request, user)
            messages.add_message(request, messages.SUCCESS,
                                 f"Здравствуйте, {user.name}! Вы успешно вошли в аккаунт.")
            return redirect('core:home')  # Перенаправление на главную страницу после успешного входа

    return render(request, 'accounts/authentication.html', {
        'registration_form': registration_form,
        'login_form': login_form
    })


def logout_view(request):
    logout(request)
    messages.add_message(request, messages.SUCCESS,
                         f"Успешный выход из аккаунта")
    return redirect('core:home')


def profile_view(request):
    booking_history = rooms.models.Booking.objects.filter(user=request.user)
    return render(request, 'accounts/profile.html', {'booking_history': booking_history})

mysite1/templates/accounts/authentication.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="page__banner" data-background="{% static 'img/page-banner/banner-1.jpg' %}">
    <div class="container">
      <div class="row">
        <div class="col-xl-12">
          <div class="page__banner-title">
            <h1>Аккаунт</h1>
            <div class="page__banner-title-menu">
              <ul>
                <li><a href="{% url 'core:home' %}">Главная</a></li>
                <li><span>-</span>Авторизация</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="form-wrapper pt-100 mb-70">
    <div class="container">
      <h2 class="text-center mb-5 pb-4">Для продолжения войдите в аккаунт или зарегистрируйтесь</h2>
      <div class="row justify-content-around">
        <div class="col-12 col-md-5">
          <form method="POST" action="{% url 'accounts:authentication' %}">
            <h3 class="mb-3">Регистрация</h3>

            {% csrf_token %}
            {% for field in registration_form %}
              <div class="mb-4 form-floating">
                <input type="{{ field.widget_type }}"
                       id="{{ field.id_for_label }}"
                       class="form-control"
                       placeholder="{{ field.label }}"
                       name="{{ field.name }}"
                       required>
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                <div id="{{ field.name }}Help" class="form-text">{{ field.help_text }}</div>
              </div>
            {% endfor %}
            <div class="form-check mb-4">
              <input class="form-check-input" type="checkbox" value="" required id="form2Example3cg"/>
              <label class="form-check-label" for="form2Example3g">
                Я принимаю все правила <a href="#" style="color: var(--primary-color);" data-bs-toggle="modal"
                                          data-bs-target="#privacy_polite">Политики персональных данных</a>
              </label>
            </div>
            <button type="submit" class="theme-btn">Зарегистрироваться</button>
          </form>
        </div>
        <div class="col-12 col-md-5">
          <form method="POST" action="{% url 'accounts:authentication' %}">
            <h3 class="mb-3">Вход</h3>

            {% csrf_token %}
            {% for field in login_form %}
              <div class="mb-4 form-floating">
                <input type="{{ field.widget_type }}"
                       id="{{ field.id_for_label }}"
                       class="form-control"
                       placeholder="{{ field.label }}"
                       name="{{ field.name }}"
                       required>
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                <div id="{{ field.name }}Help" class="form-text">{{ field.help_text }}</div>
              </div>
            {% endfor %}

            <button type="submit" class="theme-btn">Войти</button>
          </form>
        </div>
      </div>
    </div>
  </div>




{% endblock %}

mysite1/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="page__banner small" data-background="{% static 'img/page-banner/banner-2.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="page__banner-title">
                        <h1>Профиль</h1>
                        <div class="page__banner-title-menu">
                            <ul>
                                <li><a href="{% url 'core:home' %}">Главная</a></li>
                                <li><span>-</span>Профиль</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section class="profile section-padding">
        <div class="container">
            <div class="row mb-5">
                <div class="col-12 col-lg-8">
                    <h2 class="mb-4"><b>{{ user.name }}</b></h2>
                </div>
                <div class="col-12 col-lg-4 d-flex align-items-center gap-3">
                    <div class="form-floating flex-grow-1">
                        <input class="form-control" id="profile-email" type="email" readonly value="{{ user.email }}"/>
                        <label for="profile-email" class="form-label">Email</label>
                    </div>
                    <a href="{% url 'accounts:logout' %}" title="Выйти из аккаунта"><i class="fad fa-sign-out"
                                                                                       style="color: var(--primary-color); font-size: 2.5rem;"></i></a>
                </div>
            </div>
            <div class="row gx-5 mb-4">
                <div class="col-12 col-lg-6 mb-4">
                    <img src="{% static 'img/hotel/hotel-9.jpg' %}" alt="Hotel Image" class="img__full">
                </div>
                <div class="col-12 col-lg-6 mb-4">
                    <h3 class="mb-4">История:</h3>
                    <table class="table table-bordered border-light-subtle border-2">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Заезд</th>
                            <th scope="col">Выезд</th>
                            <th scope="col">Номер</th>
                            <th scope="col">Кол-во гостей</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for foo in booking_history reversed %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{ foo.check_in|date:"d.m.Y" }}</td>
                                <td>{{ foo.check_out|date:"d.m.Y" }}</td>
                                <td>{{ foo.room.title }}</td>
                                <td>{{ foo.adult_count }} взр.
                                    {% if foo.child_count %}{{ foo.child_count }} дет. {% endif %} </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

            {#			<div class="row gx-5">#}
            {#				<div class="col-12 col-lg-6">#}
            {#					<div class="balance__container">#}
            {#						<p>Бонусный счёт:</p>#}
            {#						<h1 class="fw-bold balance__count">#}
            {#							2 612 <span class="ms-3 h1"><i class="fal fa-money-bill-wave"></i></span>#}
            {#						</h1>#}
            {#					</div>#}
            {#				</div>#}
            {#				<div class="col-12 col-lg-6">#}
            {#					<h4 class="mb-2">Как получать бонусы?</h4>#}
            {#					<div class="mb-3">#}
            {#						При бронировании номеров на ваш аккаунт поступают бонусы в размере 10% от общей суммы бронирования. Но#}
            {#						Вы также можете получать бонусы пользуясь услугами в нашей гостинице:#}
            {#						<ul>#}
            {#							<li>до 7% от покупок в ресторане</li>#}
            {#							<li>от 5% до 15% за пользование бассейном и баней</li>#}
            {#							<li>до 10% при покупках в магазинах "Сластёна" и "Петровский"</li>#}
            {#							<li>при участии в акциях, розыгрышах и других мероприятий гостиницы</li>#}
            {#						</ul>#}
            {#						Обмен бонусов на рубли производится по следующему курсу: <b>2 бонуса = 1 рубль</b>#}
            {#					</div>#}
            {#					<h4 class="mb-2">Как тратить и использовать бонусы?</h4>#}
            {#					<p class="mb-3">#}
            {#						Бонусами можно польностью покрыть плату за бронирование номера, оплачивать услуги гостиницы или просто#}
            {#						вывести их на свою карту. Для подробной информации обращайтесь к администраторам. <br/>#}
            {#						Обмен бонусов на рубли производится по следующему курсу: <b>2 бонуса = 1 рубль</b>#}
            {#					</p>#}
            {#				</div>#}
            {#			</div>#}
        </div>
    </section>

{% endblock %}