mysite1/core/urls.py
from django.urls import path

from core.views import *

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('services/', services, name='services'),
    path('contact', contact, name='contact')
]

mysite1/mysite1/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mysite1 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('rooms/', include('rooms.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite1/core/models.py
from django.db import models

# Create your models here.

mysite1/rooms/models.py
import os
import uuid

from django.db import models
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from django.contrib.auth import get_user_model

User = get_user_model()


def upload_to(instance, filename):
    extension = filename.split('.')[-1]
    new_filename = f'{instance._meta.model_name}_{uuid.uuid4()}.{extension}'
    return os.path.join('rooms/', instance._meta.model_name, new_filename)


class Service(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to=upload_to)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    slug = models.SlugField(unique=True, max_length=255, verbose_name='URL-адрес')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Room(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    description = models.TextField(verbose_name='Полное описание')
    short_description = models.TextField(max_length=100, verbose_name='Короткое описание')
    main_image = models.ImageField(upload_to=upload_to, verbose_name='Превью')
    services = models.ManyToManyField(Service, verbose_name='Услуги номера')
    slider_images = models.ManyToManyField('RoomImage', related_name='room_slider', verbose_name='Изображения слайдера',
                                           blank=True)
    is_available = models.BooleanField(default=True, verbose_name='Свободен')
    max_adults = models.IntegerField(default=2, verbose_name='Макс. взрослых')
    max_children = models.IntegerField(default=0, verbose_name='Макс. детей')
    slug = models.SlugField(unique=True, max_length=255, verbose_name='URL-адрес')
    check_in = models.DateField(verbose_name='Дата заезда', blank=True, null=True)
    check_out = models.DateField(verbose_name='Дата выезда', blank=True, null=True)
    booked_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Забронировал')
    price = models.IntegerField(default=1, verbose_name='Стоимость за ночь')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            while Room.objects.filter(slug=self.slug).exists():
                self.slug = slugify(f'{self.title} {uuid.uuid4()}')
        super().save(*args, **kwargs)

    def is_booked(self):
        return self.check_in is not None and self.check_out is not None and self.check_out >= timezone.localdate()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Номер'
        verbose_name_plural = 'Номера'


class RoomImage(models.Model):
    image = models.ImageField(upload_to=upload_to, verbose_name='Ссылка')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='images', null=True, blank=True,
                             verbose_name='Номер')

    def __str__(self):
        return f'{self.room} | {os.path.basename(self.image.name)}'

    def image_tag(self):
        if self.image:
            return mark_safe(f'<img src="{self.image.url}" style="max-height:200px;"/>')
        else:
            return ''

    image_tag.short_description = 'Изображение'

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения слайдера'


class Staff(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=50)
    position = models.CharField(verbose_name='Должность', max_length=50)
    picture = models.ImageField(verbose_name='Изображение', upload_to=upload_to)
    s_link_vk = models.CharField(verbose_name='Ссылка: ВКонтакте', max_length=255, default='#', blank=True)
    s_link_tg = models.CharField(verbose_name='Ссылка: Telegram', max_length=255, default='#', blank=True)
    s_link_yt = models.CharField(verbose_name='Ссылка: YouTube', max_length=255, default='#', blank=True)
    s_link_ph = models.CharField(verbose_name='Телефон', max_length=255, default='#', blank=True)
    main = models.BooleanField(verbose_name='Отображать на главной странице', default=False)

    def __str__(self):
        return f'{self.position}: {self.name}'

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'


class Booking(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, verbose_name='Номер')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', null=True, blank=True)
    date_booked = models.DateTimeField(verbose_name='Дата и время бронирования', auto_now_add=True)
    child_count = models.IntegerField(verbose_name='Кол-во детей', blank=True, null=True)
    adult_count = models.IntegerField(verbose_name='Кол-во взрослых')
    check_in = models.DateField(verbose_name='Дата заезда')
    check_out = models.DateField(verbose_name='Дата выезда')
    guest_name = models.CharField(max_length=255, verbose_name='Имя гостя', blank=True)
    guest_email = models.EmailField(max_length=255, verbose_name='Электронная почта', blank=True, null=True)
    guest_phone = models.CharField(max_length=20, verbose_name='Телефон', blank=True, null=True)
    price = models.IntegerField(verbose_name='Стоимость проживания', blank=True, null=True)

    def __str__(self):
        return f'{self.guest_name} забронировал номер "{self.room.title}" {self.date_booked.strftime("%d.%m.%Y")}'

    class Meta:
        verbose_name = 'Бронирование'
        verbose_name_plural = 'Бронирования'

mysite1/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from .models import User


class RegistrationForm(UserCreationForm):
    name = forms.CharField(required=True, label='Ваше имя и фамилия')
    email = forms.EmailField(required=True, label='Ваш Email-адрес')

    class Meta:
        model = User
        fields = ('name', 'email', 'password1', 'password2')


class LoginForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(widget=forms.PasswordInput)

    def authenticate_user(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        return user

mysite1/rooms/forms.py
from django import forms
from django.utils import timezone
from rooms.models import Room, RoomImage
from .models import Booking


class RoomImageForm(forms.ModelForm):
    class Meta:
        model = RoomImage
        fields = '__all__'


class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = '__all__'

    slider_images = forms.ModelMultipleChoiceField(
        queryset=RoomImage.objects.all(),
        widget=forms.SelectMultiple,
        required=False,
    )


class BookingForm(forms.ModelForm):
    check_in = forms.DateField(
        label='Дата заезда',
        widget=forms.DateInput(attrs={'type': 'date', 'min': timezone.localdate().strftime('%Y-%m-%d'), 'value': timezone.localdate().strftime('%Y-%m-%d')}),
        input_formats=['%Y-%m-%d'],
        required=True
    )
    check_out = forms.DateField(
        label='Дата выезда',
        widget=forms.DateInput(attrs={'type': 'date', 'min': timezone.localdate().strftime('%Y-%m-%d'), 'value': timezone.localdate().strftime('%Y-%m-%d')}),
        input_formats=['%Y-%m-%d'],
        required=True
    )
    room_choice = forms.ModelChoiceField(
        queryset=Room.objects.all(),
        label='Номер',
        widget=forms.Select(attrs={'class': 'form-select', 'size': 6, 'onchange': "showRoomInfo(this)"}),
        required=True
    )
    adult_count = forms.IntegerField(
        label='Количество взрослых',
        widget=forms.NumberInput(attrs={'min': 1, 'max': 4}),
        required=True
    )
    child_count = forms.IntegerField(
        label='Количество детей',
        widget=forms.NumberInput(attrs={'min': 0, 'max': 4}),
        required=False
    )
    user_name = forms.CharField(
        label='Имя',
        widget=forms.TextInput(attrs={'readonly': 'readonly'}),
        required=False, help_text='Имя гостя установлено исходя из данных аккаунта пользователя'
    )
    user_email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={'readonly': 'readonly'}),
        required=False,
        help_text='Email гостя установлено исходя из данных аккаунта пользователя'
    )
    guest_phone = forms.CharField(
        label='Телефон',
        widget=forms.TextInput(attrs={'placeholder': "8 (___) ___ __-__"}),
        required=True
    )

    class Meta:
        model = Booking
        fields = ['guest_name', 'guest_email', 'guest_phone', 'user_name', 'user_email', 'adult_count', 'child_count']

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request', None)  # Извлекаем request из kwargs
        super().__init__(*args, **kwargs)

        if request and request.user.is_authenticated:
            del self.fields['guest_name']
            del self.fields['guest_email']
            self.fields['user_name'].initial = request.user.name
            self.fields['user_email'].initial = request.user.email
        else:
            del self.fields['user_name']
            del self.fields['user_email']

mysite1/core/views.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError
from django.http import JsonResponse
from django.shortcuts import render, redirect
from rooms.models import Room, Service, Staff, RoomImage


def home(request):
    rooms = Room.objects.all()
    services = Service.objects.all()
    staff = Staff.objects.filter(main=True)
    return render(request, 'core/home.html', {
        'rooms': rooms,
        'services': services,
        'staff': staff,
    })


def services(request):
    gallery = RoomImage.objects.all()
    services = Service.objects.all()
    staff = Staff.objects.all()
    return render(request, 'core/sevices.html', {
        'gallery': gallery,
        'services': services,
        'staff': staff,
    })


def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        # Отправка email
        try:
            send_mail(
                subject,
                f'Имя: {name}\nEmail: {email}\nТелефон: {phone}\nСообщение: {message}',
                settings.EMAIL_HOST_USER,
                [settings.EMAIL_HOST_USER],
            )
        except BadHeaderError:
            messages.add_message(request, messages.ERROR,
                                 "Не удалось отправить сообщение. Перезагрузите страницу и попробуйте ещё раз")

        messages.add_message(request, messages.INFO, "Сообщение отправлено")
        return redirect('core:contact')
    return render(request, 'core/contact.html', {})

mysite1/templates/core/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

	<!-- Page Banner Start -->
	<div class="page__banner" data-background="{% static 'img/page-banner/banner-1.jpg' %}">
		<div class="container">
			<div class="row">
				<div class="col-xl-12">
					<div class="page__banner-title">
						<h1>О нас</h1>
						<div class="page__banner-title-menu">
							<ul>
								<li><a href="{% url 'core:home' %}">Главная</a></li>
								<li><span>-</span>О нас</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Page Banner End -->
	<!-- Company Offers Start -->
	<div class="offers__area section-padding">
		<div class="container">
			<div class="row mb-5">
				<div class="col-xl-12">
					<div class="offers__area-title scroll-effect">
						<span class="subtitle__one">Скидки</span>
						<h2>Забронируй номер сейчас и получи скидку 35%</h2>
						<p>Мы запускаем новую систему бронирования, и благодаря Вам мы хотим её протестировать. В связи с этим мы
							запускаем акцию: при бронировании номера действует <b> скидка 35% </b> от стоимости! Мы будем рады
							услышать ваши отзывы о работе системы и нам будет полезна любая информация о вашем опыте использования.
						</p>
						<small>Срок действия акции: с 31.12.2022 по 31.12.2023 включительно</small>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xl-12">
					<div class="offers__area-image scroll-effect">
						<img class="img__full" src="{% static 'img/features/offers.jpg' %}" alt="">
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Company Offers End -->
	<!-- Services Two Start -->
	<section class="services__two section-padding pt-0">
		<div class="container">
			<div class="row mb-4 justify-content-center">
				{% for service in services|slice:':8' %}
					<div class="col-xl-3 col-lg-4 col-md-6 xl-mb-30">
						<div class="services__two-item scroll-effect">
							<span>0{{ forloop.counter }}</span>
							<div class="services__two-item-icon">
								<img src="{{ service.image.url }}" alt="{{ service.title }}" width="60" height="60">
							</div>
							<div class="services__two-item-content">
								<h4>{{ service.title }}</h4>
								<p>{{ service.description }}</p>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</section>
	<!-- Services Two End -->
	<!-- Gallery Area Start -->
	<div class="gallery__area section-padding pb-0 overflow-hidden">
		<div class="container-fluid p-0">
			<div class="row row-cols-2 row-cols-lg-3 row-cols-xl-4">
				{% for img in gallery %}
					<div class="col mb-4 scroll-effect">
						<div class="gallery__area-item">
							<a class="img-popup" href="{{ img.image.url }}">
								<img class="img__full gallery-img"
								     src="{{ img.image.url }}"
								     alt="">
							</a>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
	<!-- Gallery Area End -->
	<!-- Team Area Start -->
	<section class="team__area section-padding">
		<div class="container">
			<div class="row mb-60">
				<div class="col-xl-12">
					<div class="team__area-title scroll-effect">
						<span class="subtitle__one">Наша команда</span>
						<h2>Профессионалы позаботятся о Вас</h2>
					</div>
				</div>
			</div>
			<div class="row justify-content-center">
				{% for person in staff|slice:':3' %}
					<div class="col-12 col-md-6 col-xl-4 xl-mb-30">
						<div class="team__area-item scroll-effect">
							<div class="team__area-item-image">
								<img src="{{ person.picture.url }}" alt="">
								<div class="team__area-item-image-overlay">
									<div class="team__area-item-image-overlay-social">
										<ul>
											<li><a href="{{ person.s_link_vk }}"><i class="fab fa-vk"></i></a></li>
											<li><a href="{{ person.s_link_tg }}"><i class="fas fa-paper-plane"></i></a></li>
											<li><a href="{{ person.s_link_yt }}"><i class="fab fa-youtube"></i></a></li>
											<li><a href="tel:{{ person.s_link_ph }}"><i class="fas fa-phone"></i></a></li>
										</ul>
									</div>
									<div class="team__area-item-image-overlay-content">
										<h5>{{ person.name }}</h5>
										<span>{{ person.position }}</span>
									</div>
								</div>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</section>
	<!-- Team Area End -->

{% endblock %}

mysite1/templates/core/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- Page Banner Start -->
  <div class="page__banner" data-background="{% static 'img/page-banner/banner-3.jpg' %}">
    <div class="container">
      <div class="row">
        <div class="col-xl-12">
          <div class="page__banner-title">
            <h1>Контактная информация</h1>
            <div class="page__banner-title-menu">
              <ul>
                <li><a href="index.html">Главная</a></li>
                <li><span>-</span>Контакты</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Page Banner End -->
  <!-- Contact Area Start -->
  <div class="contact__area section-padding pb-0">
    <div class="container">
      <div class="row">
        <div class="col-xl-5 col-lg-5 lg-mb-30">
          <div class="contact__area-title">
            <h3 class="mb-25">Связаться с нами</h3>
            <p></p>
          </div>
          <div class="contact__area-info">
            <div class="contact__area-info-item">
              <div class="contact__area-info-item-icon">
                <i class="fal fa-phone-alt"></i>
              </div>
              <div class="contact__area-info-item-content">
                <span>Телефон</span>
                <h6><a href="tel:+7(902)1905585">+7 (902) 190-55-85</a></h6>
              </div>
            </div>
            <div class="contact__area-info-item">
              <div class="contact__area-info-item-icon">
                <i class="fal fa-envelope"></i>
              </div>
              <div class="contact__area-info-item-content">
                <span>Email-адрес</span>
                <h6><a href="mailto:contact.hotel@pearl.com">contact.hotel@pearl.com</a></h6>
              </div>
            </div>
            <div class="contact__area-info-item">
              <div class="contact__area-info-item-icon">
                <i class="fal fa-map-marker-alt"></i>
              </div>
              <div class="contact__area-info-item-content">
                <span>Адрес</span>
                <h6><a href="#">Россия, Вологда, ул. Первомайская, дом 42</a></h6>
              </div>
            </div>
            <div class="contact__area-info-item">
              <div class="contact__area-info-item-icon">
                <i class="fal fa-clock"></i>
              </div>
              <div class="contact__area-info-item-content">
                <span>Режим работы</span>
                <h6>Круглосуточно</h6>
              </div>
            </div>
          </div>
          <div class="contact__area-social">
            <ul>
              <li><a href="#"><i class="fab fa-vk"></i></a>
              </li>
              <li><a href="#"><i class="fas fa-paper-plane"></i></a>
              </li>
              <li><a href="#"><i class="fab fa-youtube"></i></a>
              </li>
              <li><a href="#"><i class="fas fa-phone"></i></a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-xl-7 col-lg-7">
          <div class="contact__area-form">
            <h3 class="mb-35">Отправить сообщение</h3>
	          <p id="form-info-text">Заполните данную форму и ожидайте звонок администратора</p>
            <form action="#" method="post">
	            {% csrf_token %}
              <div class="row">
                <div class="col-sm-6 mb-30">
                  <label for="id_name" class="mb-2 fw-semibold">Имя и фамилия</label>
                  <div class="contact__area-form-item">
                    <i class="fal fa-user"></i>
                    <input type="text" name="name" id="id_name" placeholder="Пётр Петров" required="required">
                  </div>
                </div>
                <div class="col-sm-6 sm-mb-30">
                  <label for="id_email" class="mb-2 fw-semibold">Email-адрес</label>
                  <div class="contact__area-form-item">
                    <i class="far fa-envelope-open"></i>
                    <input type="email" name="email" id="id_email" placeholder="petrova@example.ru" required="required">
                  </div>
                </div>
                <div class="col-sm-6 mb-30">
                  <label for="id_guest_phone" class="mb-2 fw-semibold">Телефон</label>
                  <div class="contact__area-form-item">
                    <i class="far fa-phone-alt"></i>
                    <input type="text" name="phone" id="id_guest_phone" placeholder="8 (___) ___ __-__" required="required">
                  </div>
                </div>
                <div class="col-sm-6 sm-mb-30">
                  <label for="id_subject" class="mb-2 fw-semibold">Тема сообщения</label>
                  <div class="contact__area-form-item">
                    <i class="far fa-address-book"></i>
                    <input type="text" name="subject" id="id_subject" placeholder="Я бы хотел..." required="required">
                  </div>
                </div>
                <div class="col-sm-12 mb-30">
                  <label for="id_message" class="mb-2 fw-semibold">Сообщение</label>
                  <div class="contact__area-form-item">
                    <i class="far fa-comments"></i>
                    <textarea name="message" id="id_message" placeholder="Как я могу..." required="required"></textarea>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="contact__area-form-item">
                    <button class="theme-btn" type="submit">Отправить<i class="fal fa-long-arrow-right"></i></button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xl-12">
          <div class="contact__area-map section-padding">
            <div id="contact__yandex-map" style="height: 450px;"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Contact Area End -->
  <script src="https://api-maps.yandex.ru/2.1/?apikey=3d8be71b-c57d-44c1-8738-f8ec42f50612&lang=ru_RU" type="text/javascript"></script>
   <!-- Yandex Maps -->
  <script type="text/javascript">
    // Функция ymaps.ready() будет вызвана, когда
    // загрузятся все компоненты API, а также когда будет готово DOM-дерево.
    ymaps.ready(init);

    function init() {
      // Создание карты.
      let contactsMap = new ymaps.Map('contact__yandex-map', {
        // Координаты центра карты.
        // Порядок по умолчанию: «широта, долгота».
        // Чтобы не определять координаты центра карты вручную,
        // воспользуйтесь инструментом Определение координат.
        center: [59.208429, 39.892744],
        // Уровень масштабирования. Допустимые значения:
        // от 0 (весь мир) до 19.
        zoom: 14,
        controls: ['routeButtonControl'],
      });
      let hotelPoint = new ymaps.Placemark([59.208429, 39.892744], {}, {
        preset: 'islands#redDotIcon'
      });

      contactsMap.geoObjects.add(hotelPoint)
    }
  </script>
  {% endblock %}

mysite1/templates/core/sevices.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <!-- Page Banner Start -->
    <div class="page__banner" data-background="{% static 'img/page-banner/banner-1.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="page__banner-title">
                        <h1>Об отеле</h1>
                        <div class="page__banner-title-menu">
                            <ul>
                                <li><a href="{% url 'core:home' %}">Главная</a></li>
                                <li><span>-</span>Об отеле</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Page Banner End -->
    <!-- Company Offers Start -->
    <div class="offers__area section-padding pb-0">
        <div class="container">
            <div class="row mb-5">
                <div class="col-xl-12">
                    <div class="offers__area-title scroll-effect">
                        <span class="subtitle__one">Об отеле</span>
                        <h2>Гостиничный комплекс <b>"ЖЕМЧУГ"</b></h2>
                        <p><strong>ЖЕМЧУГ</strong> - ваш комфортный уголок в историческом сердце города Вологда. Расположенный в нескольких минутах ходьбы от основных достопримечательностей и деловых районов, наш отель предлагает идеальное сочетание современного комфорта и уникального колорита Вологды.</p>
                        <p><strong>ЖЕМЧУГ</strong> предлагает разнообразие просторных и элегантно оформленных номеров, от классических одноместных до роскошных люксов. Каждый номер оборудован современными удобствами, включая бесплатный Wi-Fi, кондиционер, мини-бар и телевизор с плоским экраном. Гостям также доступны услуги прачечной, круглосуточное обслуживание номеров и услуги проката автомобилей.</p>
                        <p><strong>ЖЕМЧУГ</strong> является идеальным выбором для тех, кто ищет комфортное проживание, великолепное обслуживание и прекрасное местоположение в Вологде. Мы стремимся сделать ваше пребывание незабываемым и полным удовольствия. Добро пожаловать в отель "Северная Звезда"!</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-12">
                    <div class="offers__area-image scroll-effect">
                        <img class="img__full" src="{% static 'img/page-banner/banner-2.jpg' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Company Offers End -->
    <!-- Company Offers Start -->
    <div class="offers__area section-padding">
        <div class="container">
            <div class="row mb-5">
                <div class="col-xl-12">
                    <div class="offers__area-title scroll-effect">
                        <span class="subtitle__one">Скидки</span>
                        <h2>Забронируй номер сейчас и получи скидку 35%</h2>
                        <p>Мы запускаем новую систему бронирования, и благодаря Вам мы хотим её протестировать. В связи
                            с этим мы
                            запускаем акцию: при бронировании номера действует <b> скидка 35% </b> от стоимости! Мы
                            будем рады
                            услышать ваши отзывы о работе системы и нам будет полезна любая информация о вашем опыте
                            использования.
                        </p>
                        <small>Срок действия акции: с 31.12.2022 по 31.12.2023 включительно</small>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-12">
                    <div class="offers__area-image scroll-effect">
                        <img class="img__full" src="{% static 'img/features/offers.jpg' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Company Offers End -->
    <!-- Services Two Start -->
    <section class="services__two section-padding pt-0">
        <div class="container">
            <div class="row mb-4 justify-content-center">
                {% for service in services %}
                    <div class="col-xl-3 col-lg-4 col-md-6 xl-mb-30">
                        <div class="services__two-item scroll-effect">
                            <span>0{{ forloop.counter }}</span>
                            <div class="services__two-item-icon">
                                <img src="{{ service.image.url }}" alt="{{ service.title }}" width="60" height="60">
                            </div>
                            <div class="services__two-item-content">
                                <h4>{{ service.title }}</h4>
                                <p>{{ service.description }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Services Two End -->
    <!-- Gallery Area Start -->
    <div class="gallery__area section-padding pb-0 overflow-hidden">
        <div class="container-fluid p-0">
            <div class="row row-cols-2 row-cols-lg-3 row-cols-xl-4">
                {% for img in gallery|slice:':8' %}
                    <div class="col mb-4 scroll-effect">
                        <div class="gallery__area-item">
                            <a class="img-popup" href="{{ img.image.url }}">
                                <img class="img__full gallery-img"
                                     src="{{ img.image.url }}"
                                     alt="">
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Gallery Area End -->
    <!-- Team Area Start -->
    <section class="team__area section-padding">
        <div class="container">
            <div class="row mb-60">
                <div class="col-xl-12">
                    <div class="team__area-title scroll-effect">
                        <span class="subtitle__one">Наша команда</span>
                        <h2>Профессионалы позаботятся о Вас</h2>
                    </div>
                </div>
            </div>
            <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 justify-content-center">
                {% for person in staff %}
                    <div class="col mb-30">
                        <div class="team__area-item scroll-effect">
                            <div class="team__area-item-image">
                                <img src="{{ person.picture.url }}" alt="">
                                <div class="team__area-item-image-overlay">
                                    <div class="team__area-item-image-overlay-social">
                                        <ul>
                                            <li><a href="{{ person.s_link_vk }}"><i class="fab fa-vk"></i></a></li>
                                            <li><a href="{{ person.s_link_tg }}"><i class="fas fa-paper-plane"></i></a>
                                            </li>
                                            <li><a href="{{ person.s_link_yt }}"><i class="fab fa-youtube"></i></a></li>
                                            <li><a href="tel:{{ person.s_link_ph }}"><i class="fas fa-phone"></i></a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="team__area-item-image-overlay-content">
                                        <h5>{{ person.name }}</h5>
                                        <span>{{ person.position }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Team Area End -->
{% endblock %}